#!/usr/bin/env python3

import argparse
import scanpy as sc
import rapids_singlecell as rsc
from anndata import AnnData


def add_harmony(adata: AnnData):
    print("Running Harmony integration")
    rsc.pp.harmony_integrate(adata, args.batch_key, flavor="harmony1")


def main(args: argparse.Namespace):
    adata = sc.read_h5ad(args.adata_input)  # type: ignore
    # Operations done in place
    add_harmony(adata)

    # 9. Save the adata
    adata.write_h5ad(filename=args.adata_output, compression="lzf")

    # Save metadata
    metatable = adata.obs
    metatable["UMAP_1"] = adata.obsm["X_umap"][:, 0]
    metatable["UMAP_2"] = adata.obsm["X_umap"][:, 1]
    metatable.to_csv(args.output_metadata_file, index=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Add Harmony integration")
    parser.add_argument(
        "--batch-key",
        type=str,
        required=True,
        help="Key in AnnData object for batch information",
    )
    parser.add_argument(
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset",
    )
    parser.add_argument(
        "--adata-output",
        type=str,
        required=True,
        help="Output file to save AnnData object to",
    )
    parser.add_argument(
        "--output-metadata-file",
        type=str,
        required=True,
        help="Output file to write metadata to",
    )

    args = parser.parse_args()
    main(args)
